<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <InvariantGlobalization>true</InvariantGlobalization>
    <IncludeHttpRuleProtos>true</IncludeHttpRuleProtos>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <DocumentationFile>bin\GrpcGreeter.xml</DocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn>
    <PackageId>ServiceHub.ApiV1</PackageId>
    <Version>1.0.1</Version>
    <Author>ADuke</Author>
    <Product>ApiV1</Product>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google.Protobuf" Version="3.27.2" />
    <PackageReference Include="Grpc.Net.Client" Version="2.63.0" />
    <PackageReference Include="Grpc.Tools" Version="2.64.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.Grpc.JsonTranscoding" Version="8.0.6" />
    <PackageReference Include="Microsoft.AspNetCore.Grpc.Swagger" Version="0.8.6" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="8.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Polly" Version="8.4.1" />
    <PackageReference Include="Serilog.AspNetCore" Version="8.0.1" />
    <PackageReference Include="Serilog.Extensions.Logging" Version="8.0.0" />
    <PackageReference Include="protobuf-net" Version="3.2.30" />
    <PackageReference Include="ProtoValidate" Version="0.1.3" />
    <PackageReference Include="Serilog.Formatting.Compact" Version="3.0.0" />
    <PackageReference Include="ServiceHub.AKSMiddleware" Version="1.0.0" />
    <PackageReference Include="ServiceHub.LogProto" Version="1.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore.Swagger" Version="6.6.2" />
    <PackageReference Include="System.Runtime" Version="4.3.1" />
    <PackageReference Include="System.Threading.Tasks" Version="4.3.0" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="Proto/api.proto" GrpcServices="Both" ProtoRoot="Proto" />
  </ItemGroup>

</Project>