<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <InvariantGlobalization>true</InvariantGlobalization>
    <IncludeHttpRuleProtos>true</IncludeHttpRuleProtos>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ADuke.Middleware.ListInterceptors" Version="1.0.0" />
    <PackageReference Include="Google.Protobuf" Version="3.27.1" />
    <PackageReference Include="Grpc.AspNetCore" Version="2.63.0" />
    <PackageReference Include="Grpc.Tools" Version="2.64.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="microsoft.aspnetcore.grpc.jsontranscoding" Version="8.0.6" />
    <PackageReference Include="Microsoft.AspNetCore.Grpc.Swagger" Version="0.8.6" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="8.0.0" />
    <PackageReference Include="Serilog" Version="4.0.0" />
    <PackageReference Include="Serilog.Extensions.Logging" Version="8.0.0" />
    <PackageReference Include="Serilog.Formatting.Compact" Version="3.0.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.0.0" />
    <PackageReference Include="System.CommandLine" Version="2.0.0-beta4.22272.1" />
    <PackageReference Include="System.CommandLine.NamingConventionBinder" Version="2.0.0-beta4.22272.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\api\v1\GrpcServiceGenerator.csproj" />
  </ItemGroup>

  <ItemGroup Condition="'$(Configuration)' == 'Client'">
    <Compile Include="cmd\Client\*.cs" />
  </ItemGroup>

  <ItemGroup Condition="'$(Configuration)' == 'Server'">
    <Compile Include="cmd\Server\*.cs" />
    <Compile Include="Internal\Server\*.cs" />
  </ItemGroup>

</Project>
